export const TOGGLE_AGREEMENT_MODAL = 'ins/eosago/TOGGLE_AGREEMENT_MODAL';
export type TOGGLE_AGREEMENT_MODAL = typeof TOGGLE_AGREEMENT_MODAL;

export const TOGGLE_SUBSCRIBE_MODAL = 'ins/eosago/TOGGLE_SUBSCRIBE_MODAL';
export type TOGGLE_SUBSCRIBE_MODAL = typeof TOGGLE_SUBSCRIBE_MODAL;
