export const GET_BRANDS_REQUEST = 'ins/eosago/GET_BRANDS_REQUEST';
export type GET_BRANDS_REQUEST = typeof GET_BRANDS_REQUEST;

export const GET_BRANDS_SUCCESS = 'ins/eosago/GET_BRANDS_SUCCESS';
export type GET_BRANDS_SUCCESS = typeof GET_BRANDS_SUCCESS;

export const GET_BRANDS_FAILURE = 'ins/eosago/GET_BRANDS_FAILURE';
export type GET_BRANDS_FAILURE = typeof GET_BRANDS_FAILURE;

export const GET_MODELS_REQUEST = 'ins/eosago/GET_MODELS_REQUEST';
export type GET_MODELS_REQUEST = typeof GET_MODELS_REQUEST;

export const GET_MODELS_SUCCESS = 'ins/eosago/GET_MODELS_SUCCESS';
export type GET_MODELS_SUCCESS = typeof GET_MODELS_SUCCESS;

export const GET_MODELS_FAILURE = 'ins/eosago/GET_MODELS_FAILURE';
export type GET_MODELS_FAILURE = typeof GET_MODELS_FAILURE;
